# Generated by Django 5.0.6 on 2024-08-02 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OverturemapsSourceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property", models.CharField(blank=True, max_length=100, null=True)),
                ("dataset", models.CharField(max_length=100)),
                ("record_id", models.CharField(max_length=100)),
                ("confidence", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OverturemapsBuildingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geo_id", models.CharField(max_length=100)),
                ("version", models.IntegerField()),
                ("update_time", models.DateTimeField()),
                ("has_parts", models.BooleanField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        to="overturemaps_wfsserver_app.overturemapssourcemodel"
                    ),
                ),
            ],
        ),
    ]
