# Generated by Django 3.2.25 on 2024-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overturemaps_wfsserver_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBOXRequestBuildingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('min_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('max_x', models.FloatField()),
                ('max_y', models.FloatField()),
            ],
        ),
    ]
