# Generated by Django 5.0.6 on 2024-10-29 23:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("overturemaps_wfsserver_app", "0003_auto_20240806_1631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overturemapsbuildingmodel",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
