# Generated by Django 3.2.25 on 2024-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overturemaps_wfsserver_app', '0004_alter_overturemapsbuildingmodel_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='classtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='num_floors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='roof_direction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='roof_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='roof_shape',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='overturemapsbuildingmodel',
            name='subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
